name: Zip e Publica no Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Criar arquivo ZIP da Lambda
        run: |
          zip lambda_function.zip lambda_function.py

      - name: Criar/Atualizar tag latest
        run: |
          git fetch --tags
          if git rev-parse latest >/dev/null 2>&1; then
            git tag -d latest
            git push origin :refs/tags/latest
          fi
          git tag latest
          git push origin latest

      - name: Criar ou atualizar Release latest
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          name: "Release Lambda - Latest"
          files: lambda_function.zip
          prerelease: false
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}